# =============================================================================
# DOCKER COMPOSE - PRODUCTION (Coolify)
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL Database
  # ---------------------------------------------------------------------------
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - timemanager_db_data:/var/lib/postgresql/data
    networks:
      - timemanager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  # ---------------------------------------------------------------------------
  # Symfony Backend API
  # ---------------------------------------------------------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: "0"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    networks:
      - timemanager_network
    depends_on:
      database:
        condition: service_healthy

  # ---------------------------------------------------------------------------
  # React Frontend (Nginx)
  # ---------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    ports:
      - "3004:80"
    networks:
      - timemanager_network
    depends_on:
      - backend

volumes:
  timemanager_db_data:

networks:
  timemanager_network:
    driver: bridge
